version: '3.9'
services:
  php-cs-fixer:
    image: 284217034260.dkr.ecr.us-east-1.amazonaws.com/docker-php:8.1
    init: true
    volumes:
      - .:/application:delegated
    entrypoint: vendor/bin/php-cs-fixer
    command: fix --verbose --show-progress=estimating

  composer:
    image: 284217034260.dkr.ecr.us-east-1.amazonaws.com/docker-php:8.1
    init: true
    volumes:
      - .:/application:delegated
      - ../soap-sdks:/soap-sdks:delegated
      - composer-cache:/root/.composer/cache:cached
      - ${COMPOSER_HOME:-~/.composer}/auth.json:/root/.composer/auth.json:cached
    environment:
      LINIO_ENV: local
      XDEBUG_CONFIG: client_host=host.docker.internal
      XDEBUG_ENV: enabled
      XDEBUG_MODE: develop,debug
    entrypoint:
      - linio-php-entrypoint
      - composer

  php:
    image: 284217034260.dkr.ecr.us-east-1.amazonaws.com/docker-php:8.1
    init: true
    volumes:
      - .:/application:delegated
      - ../soap-sdks:/soap-sdks:delegated
    environment:
      LINIO_ENV: local
      XDEBUG_CONFIG: client_host=host.docker.internal
      XDEBUG_ENV: enabled
      XDEBUG_MODE: develop,debug

volumes:
  composer-cache: ~
